### ISSUE TITLE
2023 DLC Cars + 1.9.3 720S Evo

### ISSUE THREAD

**Issue by Aeurias** [manucabral/acc-discord-rpc#1]
Missing these cars, causing it to close.

porsche_992_gt3_r
porsche_992_gt3_cup
ferrari_296_gt3
mclaren_720s_gt3_evo
audi_r8_lms_evo_ii
lamborghini_huracan_gt3_evo... maybe others also, unsure

There are new tracks as well

**Comment by manucabral** [comment]
Thank you for your report, I will fix it.

**Comment by manucabral** [comment]
New DLC cars have been added to the new release version.
